repos:
-   repo: local
    hooks:
    - id: ruff-format
      name: ruff-format
      entry: ruff format .
      language: python
      pass_filenames: false
      types: [python]
      stages: [commit]
-   repo: local
    hooks:
    - id: ruff-check
      name: ruff-check
      entry: ruff check --fix .
      language: python
      pass_filenames: false
      types: [python]
      stages: [commit]
-   repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy .
      pass_filenames: false
      language: python
      types: [python]
      stages: [commit]
-   repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest
        pass_filenames: false
        always_run: true
        stages: [push]