[tool.ruff.lint]
select = [
    "F",
    "E",
    "W",
    "I",
    "ANN",
    "N",
    "T20",
    "G",
    "ARG",
    "E501",
    "UP",
    "TID",
    "TD",
    "ERA",
    "PERF",
    "C4",
]
ignore = ["ANN101","N818","E501","ANN102","G004","E902","PLR0913","T201"]
fixable = ["I001","E501", "W", "E", "D", "UP", "FA", "ISC", "PL", "FLY", "PERF", "PLC0208", "PLC0414", "PLR0202", "PLR0203", "PLR0402", "PLR1733", "PLR1736", "F401"]

[tool.ruff]
line-length = 90
target-version = "py311"
 
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]
 
[tool.ruff.lint.flake8-annotations]
mypy-init-return = true
 
[tool.ruff.lint.isort]
known-first-party = ["apps"]
section-order = [
  "future",
  "standard-library",
  "third-party",
  "first-party",
  "local-folder",
]